[package]
name = "tcp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
reticulum =  { workspace = true }
anyhow = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }

# Logging
log = { workspace = true }
env_logger = { workspace = true }
